### ISSUE TITLE
请问如何进行启动

### ISSUE THREAD

**Issue by Aleczhang13** [izhangzhihao/intellij-rainbow-fart#2]

**Comment by izhangzhihao** [comment]
不需要额外操作，安装上就好

**Comment by izhangzhihao** [comment]
同样可以通过function等关键字触发

**Comment by Aleczhang13** [comment]
您好～ 出现这样的错误
java.lang.NoClassDefFoundError: com/squareup/moshi/Moshi$Builder
	at com.github.izhangzhihao.rainbow.fart.ResourcesLoader.runActivity(ResourcesLoader.kt:21)
	at com.intellij.ide.startup.impl.StartupManagerImpl.runActivity(StartupManagerImpl.java:289)
	at com.intellij.ide.startup.impl.StartupManagerImpl.lambda$null$3(StartupManagerImpl.java:233)
	at com.intellij.openapi.project.DumbServiceImpl.doRun(DumbServiceImpl.java:434)
	at com.intellij.openapi.project.DumbServiceImpl.updateFinished(DumbServiceImpl.java:426)
	at com.intellij.openapi.project.DumbServiceImpl$TrackedEdtActivity.run(DumbServiceImpl.java:905)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:201)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:831)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$invokeLater$4(ApplicationImpl.java:310)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:80)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:128)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:46)
	at com.intellij.openapi.application.impl.FlushQueue$FlushNow.run(FlushQueue.java:184)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:974)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:847)
	at com.intellij.ide.IdeEventQueue.lambda$null$8(IdeEventQueue.java:449)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:741)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9(IdeEventQueue.java:448)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:831)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:496)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Caused by: java.lang.ClassNotFoundException: com.squareup.moshi.Moshi$Builder PluginClassLoader[izhangzhihao.rainbow.fart, 1.1] com.intellij.ide.plugins.cl.PluginClassLoader@192e76cd
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:115)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 33 more

**Comment by izhangzhihao** [comment]
试试重启IDE？另外你能贴一下这个吗？在about里面
```
IntelliJ IDEA 2020.2 EAP (Ultimate Edition)
Build #IU-202.5792.28, built on June 18, 2020
IntelliJ IDEA EAP User
Expiration date: July 18, 2020
Runtime version: 11.0.7+10-b944.12 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 10.15.5
GC: ParNew, ConcurrentMarkSweep
Memory: 4029M
Cores: 8
Registry: ide.tooltip.initialDelay=900, ide.balloon.shadow.size=0
Non-Bundled Plugins: String Manipulation, com.alayouni.ansiHighlight, GrepConsole, com.alibaba.p3c.smartfox, org.scalafmt.ScalaFmt, izhangzhihao.rainbow.fart, me.aristotll.python.typing.adder, org.nik.presentation-assistant, some.awesome, com.chrisrm.idea.MaterialThemeUI, izhangzhihao.rainbow.brackets
```

**Comment by izhangzhihao** [comment]
或者重新下载一下安装包，可能因为网络原因导致压缩包不完整。

**Comment by WangJerry666** [comment]
> 您好～ 出现这样的错误
> java.lang.NoClassDefFoundError: com/squareup/moshi/Moshi$Builder
> at com.github.izhangzhihao.rainbow.fart.ResourcesLoader.runActivity(ResourcesLoader.kt:21)
> at com.intellij.ide.startup.impl.StartupManagerImpl.runActivity(StartupManagerImpl.java:289)
> at com.intellij.ide.startup.impl.StartupManagerImpl.lambda$null$3(StartupManagerImpl.java:233)
> at com.intellij.openapi.project.DumbServiceImpl.doRun(DumbServiceImpl.java:434)
> at com.intellij.openapi.project.DumbServiceImpl.updateFinished(DumbServiceImpl.java:426)
> at com.intellij.openapi.project.DumbServiceImpl$TrackedEdtActivity.run(DumbServiceImpl.java:905)
> at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:201)
> at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:831)
> at com.intellij.openapi.application.impl.ApplicationImpl.lambda$invokeLater$4(ApplicationImpl.java:310)
> at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:80)
> at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:128)
> at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:46)
> at com.intellij.openapi.application.impl.FlushQueue$FlushNow.run(FlushQueue.java:184)
> at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
> at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
> at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
> at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
> at java.base/java.security.AccessController.doPrivileged(Native Method)
> at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
> at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
> at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:974)
> at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:847)
> at com.intellij.ide.IdeEventQueue.lambda$null$8(IdeEventQueue.java:449)
> at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:741)
> at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9(IdeEventQueue.java:448)
> at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:831)
> at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:496)
> at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
> at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
> at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
> at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
> at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
> at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
> Caused by: java.lang.ClassNotFoundException: com.squareup.moshi.Moshi$Builder PluginClassLoader[izhangzhihao.rainbow.fart, 1.1] com.intellij.ide.plugins.cl.PluginClassLoader@192e76cd
> at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:115)
> at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
> ... 33 more

我也遇到了这样的报错信息

**Comment by izhangzhihao** [comment]
你能贴一下你的about么

在 2020年6月20日，下午6:55，WangJerry666 <notifications@github.com> 写道：

﻿

您好～ 出现这样的错误
java.lang.NoClassDefFoundError: com/squareup/moshi/Moshi$Builder
at com.github.izhangzhihao.rainbow.fart.ResourcesLoader.runActivity(ResourcesLoader.kt:21)
at com.intellij.ide.startup.impl.StartupManagerImpl.runActivity(StartupManagerImpl.java:289)
at com.intellij.ide.startup.impl.StartupManagerImpl.lambda$null$3(StartupManagerImpl.java:233)
at com.intellij.openapi.project.DumbServiceImpl.doRun(DumbServiceImpl.java:434)
at com.intellij.openapi.project.DumbServiceImpl.updateFinished(DumbServiceImpl.java:426)
at com.intellij.openapi.project.DumbServiceImpl$TrackedEdtActivity.run(DumbServiceImpl.java:905)
at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:201)
at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:831)
at com.intellij.openapi.application.impl.ApplicationImpl.lambda$invokeLater$4(ApplicationImpl.java:310)
at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:80)
at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:128)
at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:46)
at com.intellij.openapi.application.impl.FlushQueue$FlushNow.run(FlushQueue.java:184)
at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
at java.base/java.security.AccessController.doPrivileged(Native Method)
at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:974)
at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:847)
at com.intellij.ide.IdeEventQueue.lambda$null$8(IdeEventQueue.java:449)
at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:741)
at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9(IdeEventQueue.java:448)
at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:831)
at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:496)
at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Caused by: java.lang.ClassNotFoundException: com.squareup.moshi.Moshi$Builder PluginClassLoader[izhangzhihao.rainbow.fart, 1.1] com.intellij.ide.plugins.cl.PluginClassLoader@192e76cd
at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:115)
at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
... 33 more

我也遇到了这样的报错信息

**Comment by izhangzhihao** [comment]
另外重新下载一下试试？

在 2020年6月20日，下午7:24，张 志豪 <izhangzhihao@hotmail.com> 写道：

﻿
你能贴一下你的about么

在 2020年6月20日，下午6:55，WangJerry666 <notifications@github.com> 写道：

﻿

您好～ 出现这样的错误
java.lang.NoClassDefFoundError: com/squareup/moshi/Moshi$Builder
at com.github.izhangzhihao.rainbow.fart.ResourcesLoader.runActivity(ResourcesLoader.kt:21)
at com.intellij.ide.startup.impl.StartupManagerImpl.runActivity(StartupManagerImpl.java:289)
at com.intellij.ide.startup.impl.StartupManagerImpl.lambda$null$3(StartupManagerImpl.java:233)
at com.intellij.openapi.project.DumbServiceImpl.doRun(DumbServiceImpl.java:434)
at com.intellij.openapi.project.DumbServiceImpl.updateFinished(DumbServiceImpl.java:426)
at com.intellij.openapi.project.DumbServiceImpl$TrackedEdtActivity.run(DumbServiceImpl.java:905)
at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:201)
at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:831)
at com.intellij.openapi.application.impl.ApplicationImpl.lambda$invokeLater$4(ApplicationImpl.java:310)
at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:80)
at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:128)
at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:46)
at com.intellij.openapi.application.impl.FlushQueue$FlushNow.run(FlushQueue.java:184)
at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
at java.base/java.security.AccessController.doPrivileged(Native Method)
at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:974)
at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:847)
at com.intellij.ide.IdeEventQueue.lambda$null$8(IdeEventQueue.java:449)
at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:741)
at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9(IdeEventQueue.java:448)
at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:831)
at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:496)
at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Caused by: java.lang.ClassNotFoundException: com.squareup.moshi.Moshi$Builder PluginClassLoader[izhangzhihao.rainbow.fart, 1.1] com.intellij.ide.plugins.cl.PluginClassLoader@192e76cd
at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:115)
at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
... 33 more

我也遇到了这样的报错信息

**Comment by izhangzhihao** [comment]
[intellij-rainbow-fart-1.1.1.zip](https://github.com/izhangzhihao/intellij-rainbow-fart/files/4807821/intellij-rainbow-fart-1.1.1.zip)

试试这个

**Comment by izhangzhihao** [comment]
这次我直接把Moshi删了，应该不会报这个错了把
[intellij-rainbow-fart-1.1.1.zip](https://github.com/izhangzhihao/intellij-rainbow-fart/files/4807857/intellij-rainbow-fart-1.1.1.zip)

**Comment by awyd234** [comment]
hi，请问下这个对版本有限制么，用pycharm 2019.1提示 incompatible with the current Pycharm version，还是说只能在IDEA上使用

**Comment by izhangzhihao** [comment]
暂时只支持2020.1以后的版本

**Comment by izhangzhihao** [comment]
我还是给老版本的支持也加上吧...

**Comment by WangJerry666** [comment]
> 这次我直接把Moshi删了，应该不会报这个错了把
> [intellij-rainbow-fart-1.1.1.zip](https://github.com/izhangzhihao/intellij-rainbow-fart/files/4807857/intellij-rainbow-fart-1.1.1.zip)

出现了新的错误…
java.lang.NoClassDefFoundError: javazoom/jl/player/Player
	at com.github.izhangzhihao.rainbow.fart.RainbowFartTypedHandler$FartTypedHandler$releaseFart$1.invokeSuspend(RainbowFartTypedHandler.kt:41)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
Caused by: java.lang.ClassNotFoundException: javazoom.jl.player.Player PluginClassLoader[izhangzhihao.rainbow.fart, 1.1.1] com.intellij.ide.plugins.cl.PluginClassLoader@2aa4a417
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:115)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 7 more

**Comment by izhangzhihao** [comment]
@WangJerry666 你能把about贴上来吧？

**Comment by WangJerry666** [comment]
CLion 2020.1.2
Build #CL-201.7846.88, built on June 3, 2020
Licensed to 家一 王
Subscription is active until May 8, 2021
For educational use only.
Runtime version: 11.0.7+10-b765.53 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
GC: ParNew, ConcurrentMarkSweep
Memory: 1987M
Cores: 12
Registry: run.processes.with.pty=TRUE, debugger.watches.in.variables=false, ide.balloon.shadow.size=0
Non-Bundled Plugins: com.corochann.plugin.clion.singlefileexecutionplugin, izhangzhihao.rainbow.fart

**Comment by izhangzhihao** [comment]
@awyd234 看了一下，有些api在2020.1之前是没有的，所以支持起来会比较麻烦，当然如果有人想做我可以告诉你们怎么做。

**Comment by awyd234** [comment]
> @awyd234 看了一下，有些api在2020.1之前是没有的，所以支持起来会比较麻烦，当然如果有人想做我可以告诉你们怎么做。

谢谢，看了下代码都是kotlin，我先尝试升级下PyCharm，如果不能用再来研究兼容

**Comment by izhangzhihao** [comment]
@WangJerry666 你是安装的zip包还是解压zip以后安装的？

**Comment by WangJerry666** [comment]
> @WangJerry666 你是安装的zip包还是解压zip以后安装的？

解决了… 是我的问题 直接安装zip包就可以了 辛苦了

**Comment by izhangzhihao** [comment]
> > @WangJerry666 你是安装的zip包还是解压zip以后安装的？
> 
> 解决了… 是我的问题 直接安装zip包就可以了 辛苦了

@Aleczhang13

**Comment by Aleczhang13** [comment]
感谢您～
