### ISSUE TITLE
Android Studio安装失败

### ISSUE THREAD

**Issue by eternallyjie** [izhangzhihao/intellij-rainbow-fart#22]
您这个插件现在只支持AS4.2以上的版本，现在正式版才发布到4.0。我们不可能用AS4.2的canary版本用来正式开发啊。所以作者是否可以支持一下正式版发布的AS版本呢？

**Comment by izhangzhihao** [comment]
如果你想贡献较旧版本的支持，我可以告诉你怎么做

**Comment by izhangzhihao** [comment]
[intellij-rainbow-fart-1.2.2.zip](https://github.com/izhangzhihao/intellij-rainbow-fart/files/4841661/intellij-rainbow-fart-1.2.2.zip)

**Comment by izhangzhihao** [comment]
试试能不能工作，注意这个版本需要安装最新的kotlin插件

**Comment by eternallyjie** [comment]
无法工作，已经安装的是最新的kotlin插件了。是需要AS版本在4.0以上吗？kotlin插件的最新版本也是分AS版本构建的。
![image](https://user-images.githubusercontent.com/30895476/85937821-9c03f180-b939-11ea-9890-5e3fca480e3a.png)
![image](https://user-images.githubusercontent.com/30895476/85937826-ab833a80-b939-11ea-8caa-a19ccf696507.png)

**Comment by izhangzhihao** [comment]
无法工作是指的什么？

**Comment by eternallyjie** [comment]
关键字触发语音就报错了。安装的kotlin插件已经是当前版本最新的了
![image](https://user-images.githubusercontent.com/30895476/85937889-6ca1b480-b93a-11ea-8a5e-c6ce6ab24f2d.png)

**Comment by izhangzhihao** [comment]
你能把报错站贴出来吗？

**Comment by eternallyjie** [comment]
com.intellij.diagnostic.PluginException: While loading class kotlin.coroutines.CoroutineContext: loader constraint violation: loader (instance of com/intellij/ide/plugins/cl/PluginClassLoader) previously initiated loading for a different type with name "kotlin/coroutines/CoroutineContext" [Plugin: izhangzhihao.rainbow.fart]
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClassInsideSelf(PluginClassLoader.java:221)
	at com.intellij.ide.plugins.cl.PluginClassLoader.tryLoadingClass(PluginClassLoader.java:165)
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:73)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at com.github.izhangzhihao.rainbow.fart.RainbowFartTypedHandler.execute(RainbowFartTypedHandler.kt:32)
	at com.jetbrains.cidr.lang.formatting.OCAutoFormatTypedHandler.execute(OCAutoFormatTypedHandler.java:58)
	at com.intellij.execution.impl.ConsoleViewImpl$MyTypedHandler.execute(ConsoleViewImpl.java:1206)
	at com.intellij.openapi.editor.impl.DefaultRawTypedHandler$1.run(DefaultRawTypedHandler.java:55)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:994)
	at com.intellij.openapi.editor.impl.DefaultRawTypedHandler.execute(DefaultRawTypedHandler.java:49)
	at com.intellij.openapi.editor.impl.EditorFactoryImpl$MyRawTypedHandler.execute(EditorFactoryImpl.java:278)
	at com.intellij.openapi.editor.actionSystem.TypedAction.lambda$actionPerformed$0(TypedAction.java:130)
	at com.intellij.reporting.FreezeLoggerImpl.runUnderPerformanceMonitor(FreezeLoggerImpl.java:28)
	at com.intellij.openapi.editor.actionSystem.TypedAction.actionPerformed(TypedAction.java:130)
	at com.intellij.openapi.editor.impl.EditorImpl.processKeyTypedNormally(EditorImpl.java:1304)
	at com.intellij.openapi.editor.impl.EditorImpl.processKeyTyped(EditorImpl.java:1289)
	at com.intellij.openapi.editor.impl.EditorImpl.processKeyTyped(EditorImpl.java:3359)
	at com.intellij.openapi.editor.impl.EditorImpl$7.keyTyped(EditorImpl.java:1119)
	at java.awt.AWTEventMulticaster.keyTyped(AWTEventMulticaster.java:239)
	at java.awt.Component.processKeyEvent(Component.java:6505)
	at javax.swing.JComponent.processKeyEvent(JComponent.java:2833)
	at java.awt.Component.processEvent(Component.java:6327)
	at java.awt.Container.processEvent(Container.java:2239)
	at java.awt.Component.dispatchEventImpl(Component.java:4899)
	at java.awt.Container.dispatchEventImpl(Container.java:2297)
	at java.awt.Component.dispatchEvent(Component.java:4721)
	at java.awt.KeyboardFocusManager.redispatchEvent(KeyboardFocusManager.java:1954)
	at java.awt.DefaultKeyboardFocusManager.dispatchKeyEvent(DefaultKeyboardFocusManager.java:842)
	at java.awt.DefaultKeyboardFocusManager.preDispatchKeyEvent(DefaultKeyboardFocusManager.java:1111)
	at java.awt.DefaultKeyboardFocusManager.typeAheadAssertions(DefaultKeyboardFocusManager.java:981)
	at java.awt.DefaultKeyboardFocusManager.dispatchEvent(DefaultKeyboardFocusManager.java:807)
	at com.intellij.ide.IdeKeyboardFocusManager.dispatchEvent(IdeKeyboardFocusManager.java:40)
	at java.awt.Component.dispatchEventImpl(Component.java:4770)
	at java.awt.Container.dispatchEventImpl(Container.java:2297)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4721)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:766)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:84)
	at java.awt.EventQueue$4.run(EventQueue.java:739)
	at java.awt.EventQueue$4.run(EventQueue.java:737)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:736)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:878)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:805)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:466)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:704)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:465)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.lang.LinkageError: loader constraint violation: loader (instance of com/intellij/ide/plugins/cl/PluginClassLoader) previously initiated loading for a different type with name "kotlin/coroutines/CoroutineContext"
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:642)
	at com.intellij.util.lang.UrlClassLoader._defineClass(UrlClassLoader.java:335)
	at com.intellij.util.lang.UrlClassLoader.defineClass(UrlClassLoader.java:330)
	at com.intellij.util.lang.UrlClassLoader._findClass(UrlClassLoader.java:294)
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClassInsideSelf(PluginClassLoader.java:218)
	... 58 more

**Comment by izhangzhihao** [comment]
[intellij-rainbow-fart-1.2.2.zip](https://github.com/izhangzhihao/intellij-rainbow-fart/files/4841682/intellij-rainbow-fart-1.2.2.zip)
试试这个

**Comment by eternallyjie** [comment]
这个包是可以的。谢谢了
