### ISSUE TITLE
导入pycharm报错了

### ISSUE THREAD

**Issue by godzeo** [izhangzhihao/intellij-rainbow-fart#4]
mac os 
pycharm 
![image](https://user-images.githubusercontent.com/64398024/85216063-f984c500-b3b2-11ea-950d-fa47539f7320.png)

![image](https://user-images.githubusercontent.com/64398024/85216059-e40f9b00-b3b2-11ea-85df-776418415259.png)

报错

java.lang.NoClassDefFoundError: org/eclipse/egit/github/core/client/GitHubClient
	at com.github.izhangzhihao.rainbow.fart.AnonymousFeedback.sendFeedback$intellij_rainbow_fart(AnonymousFeedback.kt:100)
	at com.github.izhangzhihao.rainbow.fart.AnonymousFeedbackTask.run(AnonymousFeedback.kt:233)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:932)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsync$5(CoreProgressManager.java:434)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$null$3(ProgressRunner.java:233)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:166)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:627)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:572)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:61)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:153)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:233)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.ClassNotFoundException: org.eclipse.egit.github.core.client.GitHubClient PluginClassLoader[izhangzhihao.rainbow.fart, 1.1.1] com.intellij.ide.plugins.cl.PluginClassLoader@35e1a25c
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:115)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 15 more

**Comment by izhangzhihao** [comment]
直接导入zip，不要解压.

在 2020年6月21日，上午11:33，godzeo <notifications@github.com> 写道：

﻿

mac os
pycharm
[image]<https://user-images.githubusercontent.com/64398024/85216063-f984c500-b3b2-11ea-950d-fa47539f7320.png>

[image]<https://user-images.githubusercontent.com/64398024/85216059-e40f9b00-b3b2-11ea-85df-776418415259.png>

报错

java.lang.NoClassDefFoundError: org/eclipse/egit/github/core/client/GitHubClient
at com.github.izhangzhihao.rainbow.fart.AnonymousFeedback.sendFeedback$intellij_rainbow_fart(AnonymousFeedback.kt:100)
at com.github.izhangzhihao.rainbow.fart.AnonymousFeedbackTask.run(AnonymousFeedback.kt:233)
at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:932)
at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsync$5(CoreProgressManager.java:434)
at com.intellij.openapi.progress.impl.ProgressRunner.lambda$null$3(ProgressRunner.java:233)
at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:166)
at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:627)
at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:572)
at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:61)
at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:153)
at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:233)
at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.ClassNotFoundException: org.eclipse.egit.github.core.client.GitHubClient PluginClassLoader[izhangzhihao.rainbow.fart, 1.1.1] com.intellij.ide.plugins.cl.PluginClassLoader@35e1a25c
at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:115)
at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
... 15 more

**Comment by godzeo** [comment]
是的，成功解决了，就是好像是对Java支持的还行，php python 这些 function import 匹配都不兼容，不会说话 ，只有java会说

**Comment by izhangzhihao** [comment]
你打出全名“import”，暂不支持智能提示选择的结果

在 2020年6月21日，上午11:56，godzeo <notifications@github.com> 写道：

﻿

是的，成功解决了，就是好像是对Java支持的还行，php python 这些 function import 匹配都不兼容，不会说话 ，只有java会说
